### PR TITLE
Wiki Software Arch and Toolchain diagrams

### PR DESCRIPTION
**Pull request by tcwan**
Initial EV3Dev Architecture and Toolchain Graphics files.

### CODE REVIEW

**Comment by tcwan** [comment]
Hi, I'm new to the ev3dev project and am trying to put together my understanding of how the various pieces fit together. One of the difficulties for new users and contributors is the lack of a software architecture and toolchain map of the various projects found in the ev3dev and related repositories.

I've tried to edit the Wiki to add this info but there is no way for me to include diagrams without linking it to a URL. So I'm going to create this pull request first for the *eps files.
(I've included my master file edited using Omnigraffle so that it is kept in a safe place).

I am probably missing a lot of context of how ev3dev fits together in my diagrams (especially the toolchain diagram). If there are any misconceptions or omissions please let me know and I'll update it. Nonetheless, it is not meant to be exhaustive as such a diagram would be too cumbersome.

**Comment by dlech** [comment]
Wow. I don't think anyone has really made an effort to look at how things fit together like this.

So, here are my thoughts:

### Toolchain Diagram

It's not really clear to me what the purpose of this diagram is and I'm not sure if a diagram is really the best thing for explaining toolchains. From my point of view, there is the important information about toolchains for users (as opposed to contributors):

1. Most ev3dev users use python (based on github stars and user feedback), so they don't care about toolchains at all. Same applies to other scripting languages like JavaScript.

2. People who want to use C/C++ need a toolchain for compiling. They have 4 options.

    * Use the `ev3dev/debian-$DIST-cross` Docker (or should probably say Moby now, they changed their name) images. Pros: Faster compiling because it contains a cross-compiling toolchain. Cons: You have to install Docker/Moby. You can only use libraries that have proper multiarch support in Debian.
    * Use the `ev3dev/debian-$DIST-$ARCH-cross` Docker images. Pros: Can use any library in Debian. Cons: Have to install Docker/Moby. Slower compiling because it runs using QEMU instead of using a cross-compiler.
    * Install a pre-built toolchain, such as one from Mentor Graphics, Linaro, etc. Pros: Don't need to install Docker/Moby. Cons: All vendors stopped producing pre-built toolchains compatible with EV3 in 2014. Can only use standard libraries included in the toolchain.
    * Install `build-essential` on the EV3 itself. Pros: Don't have to find/setup Docker or a cross-compiler. Can use any library in Debian. Cons: *Really* slow compiling (not a problem for small projects). Can run out of memory (and battery) for large projects.

    It is also expected that the only reason you would want to use C/C++ with ev3dev is that you are already a C/C++ expert, so you know how to write Makefiles and set compiler flags and stuff like that.

3. Go(lang) has it's own toolchain (that includes built-in cross compiler), so none of the above applies.


From the contributers point of view, a diagram might make more sense. 

Here are my thoughts on the diagram you have made.

* I don't see how the website source (ev3dev.github.io) fits in with toolchains.
* ev3dev-tools has nothing to do with toolchains
* The lmsasm assembler and disassembler are probably of more interest to people using the official LEGO firmware and not so interesting to anyone using ev3dev.
* The dockerfiles for creating the cross compiling docker images are in the docker-cross repo, not docker-libary.
* The ev3dev/debian-$DIST-$ARCH-cross docker images are missing.
* The docker-library repo and brickstrap are used to bootstrap SD card images. This doesn't have anything to do with toolchains. We just happen to be using Docker for multiple unrelated things.
* Perhaps I am missing the point and this diagram is supposed to be about how to build ev3dev and not just about toolchains, in which case, there is quite a bit missing.


### Software Architecture Diagram

Just one correction here. Language bindings are based on the ev3dev-lang specification, not on ev3devKit.

And some ideas for improvement/expansion:
* The :elephant: in the room is missing: Debian. Like the Linux kernel + the ev3dev drivers we have official Debian as the base plus a bunch of ev3dev-specific packages on top of that. (There are also some patched official Debian packages as well).
* It would be nice to explain that the ev3-kernel is based on the mainline kernel, the bb.org-kernel is based on the BeagleBoard.org kernel and the rpi-kernel is based on the Raspberry Pi Foundation kernel.
* The base ev3dev operating system "stack" consists of systemd, ConnMan, BlueZ, Avahi, OpenSSH, Brickd and Brickman.
* There are some ev3dev-specific command line tools, like `brickrun` and `ev3dev-config`.
* lms2012-compat is kind of an on-the-side/standalone thing. You can't use lms2012-compat and use other ev3dev libraries at the same time.


### Other

Here are some other practical things to consider:

* It would be nice if we could use a free, cross-platform tool to create these diagrams (e.g. LibreOffice) so that anyone can modify them.
* PNG or SVG format is probably best for displaying on the wiki. I'm not familiar with eps or if it supported in most browsers.
* ev3dev-jessie is "done". I would rather spend time on documenting ev3dev-stretch only rather than trying to do both and explain the difference between the two.

**Comment by tcwan** [comment]
Wow. Thanks for the detailed explanation. 

This started as a personal attempt at understanding the ginormous glob that is the ev3dev repository. 

I guess the goal of the diagrams are for:
1. Folks who want to have a better understanding of how the various components fit together.
2. Potential code contributors (me perhaps?) interested in working on libraries and other lower level components.

The Toolchain Diagram is probably not usable in its current form. I learnt a lot from your descriptions, and will rethink how to provide that information in a usable manner. Maybe flowcharts for some common workflows would be a better approach. 

With regards to the system architecture diagram, my first objective is to document the ev3dev specific modules, I'll take a look at how to represent the other distro-based components you mentioned as I think it is also useful info.

I agree with your comments regarding using cross-platform tools. The only thing I can say is that I hated MS Word's draw tools so I wanted to use something more suitable to the task (Dia is so-so -- it is still not as polished as I'd like. I'd say Visio is the most fit-to-task, but that is proprietary). I'll take a look at the drawing module in LibreOffice as I wasn't sure about its capabilities. 

With regards to file formats, I would like to use a vector-based format so that it is scalable. However, my experience with SVG export from the drawing programs I'm familiar with is not very encouraging. The shapes and especially font spacing are all not well preserved. PNG is an alternative fallback except that it is bitmapped. EPS was chosen as a compromise format (since PS preserves the diagram structure properly) but I don't have any strong preference.

What's specifically the new things in stretch?

**Comment by dlech** [comment]
:+1: for the flow chart idea.

> What's specifically the new things in stretch?

There is not too much new in stretch on the surface, but the versions of everything are updated. So, if you try to document both, you would end up with lots of "on jessie, use this version/branch/repo or on stretch use this ...". I think it is better to have versioned docs, so if stretch is the current version, then we just link to the stretch versions everywhere.

For example, I've started an ev3dev user's manual for stretch [here](https://github.com/ev3dev/ev3dev/tree/ev3dev-stretch/docs) that looks like [this](http://docs.ev3dev.org/en/ev3dev-stretch/). The difference between this and the wiki is that user's manual is a bit more polished whereas the wiki is just whatever anyone want to add.

Which leads me to another thought. Perhaps instead of LibraOffice, maybe we should look at what formats are supported by Sphinx and use one of them. A quick search says that there is an extension for graphviz. That might end up being too tedious though.

**Comment by tcwan** [comment]
Haha, this is quickly leading me far down the rabbit-hole.
I've not used Sphinx before, but I'll take a look at Graphviz. Having diagrams maintained and versioned along with the code is pretty useful.

**Comment by tcwan** [comment]
From what I've found out, Graphviz is a bit low level for creating flowcharts, since it doesn't really handle the flowchart angled connectors well.

See [manual flowchart generation](https://stackoverflow.com/questions/46365855/create-simple-flowchart-with-graphviz), [sorta-flowcharts](http://melp.nl/2013/08/flow-charts-in-code-enter-graphviz-and-the-dot-language/) 

In addition, the language does not support templates and [styles](https://stackoverflow.com/questions/27262465/can-you-build-reusable-styles-in-graphviz)

Instead, [diagrams](https://www.npmjs.com/package/diagrams) seem to be a better fit as it is built on node.js and can support a wider variety of diagram types and generate SVG. The only disadvantage (to me) is that I'll need to install and maintain another programming environment to use it. There is an Atom plugin for diagram but it currently does not support flowchart visualization, otherwise I'd probably recommend it as the best option unreservedly.

One good thing about diagram's flowchart.js is that it can created embedded URL links so users can click on the block to access the repository directly.

**Comment by dlech** [comment]
I don't have a strong preference on the tool as long as it can work with https://readthedocs.org that hosts the documentation. Requiring nodejs for that could be a problem.

Here is another sphinx extension that looks promising: https://mermaidjs.github.io/

**Comment by dlech** [comment]
Hmm... it looks like mermaid is nodejs based as well, it just happens to have a sphinx extension.

**Comment by tcwan** [comment]
Does it need to be auto-generated on the fly? Could we use a tool that has a 'make' step and then commit the generated SVG files?

**Comment by dlech** [comment]
Conventional wisdom says to not commit generated files, but if that is the best we can do, I don't have a problem with it.

**Comment by tcwan** [comment]
Ok. From my brief reading about mermaid, I think it is less capable compared to diagrams, at least for the features I'm interested in. I'll go ahead with diagrams first unless other alternatives come up.

**Comment by tcwan** [comment]
Wow, github managed to thread my repository updates to this conversation automatically. I'm pretty impressed :-)

By the way, the SVG preview on Github does not allow for URL clicks. You need to view it in a browser window separately. The URLs are currently best guesses, I may not have selected the most appropriate links.

**Comment by tcwan** [comment]
Please take a look at the revised diagrams:

[Related Repositories](https://github.com/tcwan/ev3dev/blob/tcwan-wiki-swarch-1/images/ev3dev-related-repositories.dot.svg)

[Software Packages](https://github.com/tcwan/ev3dev/blob/tcwan-wiki-swarch-1/images/ev3dev-software-packages.dot.svg)

[Toolchain Selection](https://github.com/tcwan/ev3dev/blob/tcwan-wiki-swarch-1/images/workflow-c-cpp.flowchart.svg)

dot is not a very precise diagram generation tool so many things don't line up well.
I've tried to capture the relationships mentioned in the earlier post, not sure if I'm still mistaken somewhere.

Edit: Updated links and names of SVG files to reflect intent.

**Comment by tcwan** [comment]
The latest version of the Wiki can be found here:
https://github.com/tcwan/ev3dev/wiki/Getting-Started-Developing-on-ev3dev

I've removed embedded URLs from the SVG files to avoid problems with github.io

**Comment by dlech** [comment]
Holy, moly, that's a lot of information. It will take a while to get through it.

**Comment by tcwan** [comment]
Haha. Take your time.

The content targets high school level users moving beyond the EV3 Programmer environment, so it might seem a bit pedantic to someone more familiar with embedded systems development.

**Comment by tcwan** [comment]
By the way, I haven't written the last 2 sections (downloading, and running/debugging), as I don't have a EV3 to test with yet.

**Comment by dlech** [comment]
I've made it a little over half way through. I pasted it into [google docs](https://docs.google.com/document/d/1eg2vukBlEnaBYhQGZw7YCvZETgxBjgb3fuudFw_AL-w/edit?usp=sharing) so that I could make specific comments.

Overall impression though is that it is *very* technical. Perhaps high school students are different where you live, but I don't know any (except for @WasabiFan) that would understand much of this. I have just skimmed over the last few pages, but I think they are more appropriate for the target audience though - it's just the parts about the toolchains that I am talking about here. If I were teaching high schoolers with ev3dev, I would just say, "we are using Python", and not admit that C/C++ even exist.

However, the information you have about C/C++ is good for people who are already intermediate or expert level C/C++ programmers who want to use ev3dev with the language they are already comfortable with as well as people who want to compile large 3rd-party software programs that don't have debian packages.

So, if I may, I would like to suggest making a page devoted specifically to the ev3dev C/C++ toolchain situation using the information you have already written.

As for the "users moving beyond the EV3 Programmer environment", currently Python is really the only option that is maintained and doesn't take hours to setup. So, I would like to focus on that combined with the ev3dev Visual Studio Code extension as the gateway for new users.

The documentation for ev3dev-stretch lives at <http://docs.ev3dev.org/en/ev3dev-stretch/>. I think it has some of the parts you are missing. It's supposed to basically be the same kind of "how to use ev3dev for beginners" guide that you are writing here, so it would be best to incorporate your work there (except for the toolchain stuff, which I think would be best on the wiki).

But, I would like to wait until you actually get an EV3 so that you know how it really works instead of making (mostly correct) educated guesses.

**Comment by WasabiFan** [comment]
I agree on all points with @dlech -- I do want to emphasize one idea though:

> So, if I may, I would like to suggest making a page devoted specifically to the ev3dev C/C++ toolchain situation using the information you have already written.

I think the toolchain information is quite valuable as an introduction for anyone using C/C++, and I see a fair number of questions on it; the key is that _not all ev3dev users use C/C++_. In general, I see these native languages used by people who are, say, testing an algorithm developed for their thesis, not learning the basics of programming.

A large part of this is the barrier to entry -- it's reasonably easy to create a `.py` file and run it, but a lot harder to get an appropriate toolchain configured and link the appropriate libraries, as you have seen. If someone doesn't know what language to start with, I will certainly always recommend Python.

---

> Overall impression though is that it is very technical. Perhaps high school students are different where you live, but I don't know any (except for @WasabiFan) that would understand much of this. I have just skimmed over the last few pages, but I think they are more appropriate for the target audience though - it's just the parts about the toolchains that I am talking about here. If I were teaching high schoolers with ev3dev, I would just say, "we are using Python", and not admit that C/C++ even exist.

Yeah, I have a hard time imagining this being something appropriate for a typical high school student. I watched one today attempt to measure an angle with a ruler...

That being said, if "high school level" was a way to refer to "not an advanced programmer", this seams more reasonable. I figure a new C/C++ user who has dabbled with other languages in the past could generally understand it.

**Comment by tcwan** [comment]
Both of you have good comments. I guess when I stated that I was targeting high school students, I was overly ambitious. My personal target audience are undergraduates working on embedded systems, that was my motivation for writing the C/C++ toolchain portion. However, once I started, I figured that there are probably lots of high school students and above (though @WasabiFan's description of casual C/C++ programmers is probably a better description since it is not age-limited) who would be interested in dipping their toes in working with embedded systems and I wanted to cover the overall cross-development process as well.

I think the problem currently is that the document is serving two purposes, one as an introduction to cross-development, and the other as a specific guide for C/C++ users starting with ev3dev. I'm not sure what is the best way to not repeat myself, since the overall flow would be the same whether using python or C/C++ (except for the library compilation part).

I'm open to suggestions as to how to merge the content with the main site. Is it better for me to fork from [ev3 stretch docs](https://github.com/ev3dev/ev3dev/tree/ev3dev-stretch/docs)?

PS. These few weeks are busy with grading for me, but I'll check in stuff from time to time.

**Comment by dlech** [comment]
For the "official" docs, I would like to focus on the Python and VS Code workflow, so if you are interested in that, then yes fork the repo you linked.

I also think that the ev3dev-specific bits about the available cross-development options have a place in the "official" docs.

Then, we can see what is left and where it fits.

**Comment by tcwan** [comment]
I've not used VSC, as I'm not invested in the Windows development environment so it is not my first thought when thinking about IDEs.

Personally, I still prefer Eclipse due to the wider usage from embedded systems tool vendors in general and my students would probably encounter it more often compared to VSC after they graduate. (Not that I am an expert on Eclipse; it is also too much of a kitchen-sink IDE and can get unwieldy quickly)

I propose to clean up my writeup to be more IDE agnostic where relevant, and then put the Eclipse info in a subsection for the IDE page.

**Comment by tcwan** [comment]
I noticed that the earlier pull request was merged into the jessie branch.
The latest updates in this pull request should be merged as well since they related only to the diagrams and not the writeup.

**Comment by dlech** [comment]
> I've not used VSC, as I'm not invested in the Windows development environment so it is not my first thought when thinking about IDEs.

FWIW, Visual Studio Code != Visual Studio. It is cross-platform (Windows/Linux/Mac). And it is somewhere between a text editor and an IDE.

> I propose to clean up my writeup to be more IDE agnostic where relevant, and then put the Eclipse info in a subsection for the IDE page.

Sounds good.


> I noticed that the earlier pull request was merged into the jessie branch.

I suppose you are referring to the one that was make in the lms2012-compat repository about using docker for cross-compiling?

> The latest updates in this pull request should be merged as well since they related only to the diagrams and not the writeup.

OK, but I'm not sure this is the right place for these images. I'm going to have to give a bit more thought on where to put this info.

**Comment by dlech** [comment]
OK, just to keep this all in one place for now and to facilitate discussion, I have created a new repo: https://github.com/ev3dev/edu-docs

Could you copy and paste this PR and the wiki changes to a new PR on that repository? That way we can see everything at once and keep all of the discussion together.

**Comment by dlech** [comment]
Actually, it will probably be easier if I just do it. Please stand by...

**Comment by dlech** [comment]
@tcwan, I have cherry-picked all of your commits from here and from your fork of the wiki to https://github.com/ev3dev/edu-docs, so let's take the conversation there. Please let me know if I missed anything.

**Pull request closed without merging**
